language: php

php:
  - 5.4
  - 5.5
before_install:
  - git submodule update --init --recursive
  
before_script:
  - pear config-set auto_discover 1
  - pear install -a pear.phing.info/phing
  - phpenv rehash

script: phing
